export const CHARACTER_FIELD_LABELS: Record<string, string> = {
  codename: "코드네임",
  tier: "분류 (MAIN/MINI)",
  role: "역할",
  agentLevel: "요원 등급",
  department: "부서",
  isPublic: "공개 여부",
  ownerId: "소유자 ID",
  previewImage: "프리뷰 이미지",
  factionCode: "세력",
  institutionCode: "기관",

  "lore.name": "이름",
  "lore.nameNative": "원어 표기",
  "lore.nickname": "별칭",
  "lore.nameEn": "이름(EN)",
  "lore.gender": "성별",
  "lore.age": "나이",
  "lore.height": "신장",
  "lore.weight": "체중",
  "lore.mainImage": "메인 이미지",
  "lore.posterImage": "포스터 이미지",
  "lore.quote": "인용문",
  "lore.appearance": "외모",
  "lore.personality": "성격",
  "lore.background": "배경",
  "lore.roleDetail": "역할 상세",
  "lore.notes": "비고",
  "lore.loreTags": "태그",
  "lore.appearsInEvents": "등장 이벤트",

  "play.className": "직군",
  "play.hp": "HP",
  "play.hpDelta": "HP Δ",
  "play.san": "SAN",
  "play.sanDelta": "SAN Δ",
  "play.def": "DEF",
  "play.defDelta": "DEF Δ",
  "play.atk": "ATK",
  "play.atkDelta": "ATK Δ",
  "play.abilityType": "능력 타입",
  "play.credit": "크레딧",
  "play.weaponTraining": "무기 훈련",
  "play.skillTraining": "기술 훈련",
  "play.equipment": "장비",
  "play.abilities": "어빌리티",

  "sheet.codename": "코드네임 (구)",
  "sheet.name": "이름 (구)",
  "sheet.mainImage": "메인 이미지 (구)",
  "sheet.posterImage": "포스터 이미지 (구)",
  "sheet.quote": "인용문 (구)",
  "sheet.gender": "성별 (구)",
  "sheet.age": "나이 (구)",
  "sheet.height": "신장 (구)",
  "sheet.appearance": "외모 (구)",
  "sheet.personality": "성격 (구)",
  "sheet.background": "배경 (구)",
  "sheet.weight": "체중 (구)",
  "sheet.className": "직군 (구)",
  "sheet.hp": "HP (구)",
  "sheet.san": "SAN (구)",
  "sheet.def": "DEF (구)",
  "sheet.atk": "ATK (구)",
  "sheet.abilityType": "능력 타입 (구)",
  "sheet.credit": "크레딧 (구)",
  "sheet.weaponTraining": "무기 훈련 (구)",
  "sheet.skillTraining": "기술 훈련 (구)",
  "sheet.equipment": "장비 (구)",
  "sheet.abilities": "어빌리티 (구)",
  "sheet.nameEn": "이름(EN) (구)",
  "sheet.roleDetail": "역할 상세 (구)",
  "sheet.notes": "비고 (구)",
};

export const CHARACTER_IMAGE_FIELDS = new Set<string>([
  "previewImage",
  "lore.mainImage",
  "lore.posterImage",
  "sheet.mainImage",
  "sheet.posterImage",
]);

export function labelForCharacterField(field: string): string {
  return CHARACTER_FIELD_LABELS[field] ?? field;
}
