/* ── Types ── */

export type {
  User,
  UserRole,
  UserStatus,
  UserPublic,
  CreateUserInput,
  Session,
  SessionResponse,
  SessionStatus,
  ResponseStatus,
  ResponseCounts,
  SessionFinalizationKind,
  SessionFinalizationTrigger,
  SessionFinalizationDeliveryState,
  SessionFinalizationReconciliationReason,
  SessionLog,
  SessionLogType,
  Character,
  AgentCharacter,
  NpcCharacter,
  CharacterType,
  CharacterTier,
  AgentLevel,
  RoleLevel,
  DepartmentCode,
  FactionCode,
  InstitutionCode,
  LegacyDepartmentCode,
  LoreSheet,
  DossierRelation,
  DossierRelationConfidence,
  DossierSessionAppearance,
  DossierPersonalityEvidenceKind,
  DossierPersonalityObservationConfidence,
  DossierPersonalityEvidence,
  DossierPersonalityObservation,
  PlaySheet,
  Equipment,
  Ability,
  AbilitySlot,
  CreateCharacterInput,
  CharacterPublic,
  CreditTransaction,
  CreditBalance,
  CreditTransactionType,
  CreateCreditTransactionInput,
  WebAllowedCreditType,
  GmDirectGrantType,
  BotOnlyCreditType,
  MasterItem,
  CharacterInventory,
  SharedInventory,
  SharedInventoryScope,
  ItemCategory,
  EquipmentSlot,
  EquipmentAction,
  EquipmentActionKind,
  EquipmentActionDamage,
  EquipmentActionConsumableCost,
  EquipmentWeaponDamageBand,
  EquipmentWeaponAttackProfile,
  EquipmentMountRules,
  EquipmentCombatProfile,
  EquipmentChargeState,
  LicenseQualification,
  ShopMeta,
  ShopPageGroup,
  CreateMasterItemInput,
  CreateInventoryInput,
  CreateSharedInventoryInput,
  WikiPage,
  WikiPageLite,
  WikiPageSummary,
  WikiCategoryFacet,
  WikiPageSummaryConnection,
  WikiPageRevision,
  CreateWikiPageInput,
  UpdateWikiPageInput,
  Notification,
  NotificationType,
  CreateNotificationInput,
  SessionReport,
  SessionReportMapPrecision,
  CreateSessionReportInput,
  RegistrarUserTip,
  CharacterChangeLog,
  CharacterChangeLogEntry,
  NewCharacterChangeLog,
  CreditPool,
  CreateCreditPoolInput,
  ShopInventory,
  ShopDailyStock,
  CreateShopInventoryInput,
  CreateShopDailyStockInput,
  StockPrice,
  StockHolding,
  StockPriceHistory,
  MrBeastSodaStockImpactDemand,
  CreateStockPriceInput,
  CreateStockHoldingInput,
  CreateStockPriceHistoryInput,
  StockMarketStatus,
  StockMarketClosureReason,
  StockMarketState,
  StockMarketSnapshot,
  StockMarketShadowPrice,
  StockMarketShadowFlow,
  StockMarketShadowState,
  StockMarketCalendarException,
  StockOrderFlowSide,
  StockOrderFlow,
  StockFlowStrength,
  StockFlowSignal,
  StockDisclosureStatus,
  StockDisclosureKind,
  StockDisclosureEffect,
  StockMajorShareholder,
  StockCompanyProfileUpdate,
  StockCompanyProfile,
  StockDisclosure,
  StockAlertKind,
  StockMarketAlertRule,
  StockMarketPreference,
  StockCorporateActionStatus,
  StockDividendAction,
  StockSplitAction,
  StockRightsOfferingAction,
  StockCorporateAction,
  StockDividendEntitlement,
  StockInvestmentSeason,
  StockSeasonPerformance,
  StockScheduledEvent,
  StockScheduledEventActor,
  StockScheduledEventStatus,
  StockScheduledEventTier,
  PlayerTrade,
  PlayerTradeKind,
  PlayerTradeStatus,
  PlayerTradeCancellationReason,
  PlayerTradeParticipant,
  PlayerTradeOffer,
  PlayerTradeItemOffer,
  PlayerTradeStockOffer,
  CreatePlayerTradeInput,
  TrpgSession,
  TrpgSessionStatus,
  UpdateTrpgSessionResult,
  CancelTrpgSessionResult,
  TrpgGuildMember,
  TrpgSessionNotification,
  TrpgNotificationKind,
  TrpgNotificationDeliveryMethod,
  ScheduledJobRun,
  ScheduledJobRunStatus,
  IntegrationOutboxEvent,
  IntegrationOutboxStatus,
  IntegrationOutboxKind,
  IntegrationDeliveryOutcome,
  IntegrationSkipReason,
  WorkerCheckpoint,
  WorkerOperationalIncident,
  LoreEntityKind,
  LoreEntityRef,
  LoreRecordStatus,
  LoreVisibility,
  LoreAccess,
  LoreSourceKind,
  LoreSourceLocatorKind,
  LoreSourceLocator,
  LoreEvidenceRef,
  LoreLineageState,
  LoreLineage,
  LoreSource,
  LoreAliasType,
  LoreAlias,
  LoreEdge,
  LoreClaimValue,
  LoreClaim,
  LoreSearchFacets,
  LoreSearchDocument,
  LoreIngestionMode,
  LoreIngestionStatus,
  LoreIngestionStats,
  LoreIngestionError,
  LoreIngestionRun,
  BureaucratVote,
  BureaucratVoteActor,
  BureaucratVoteBallot,
  BureaucratVoteChoice,
  BureaucratVoteOutcome,
  BureaucratVotePublication,
  BureaucratVotePublicationState,
  BureaucratVoteResolution,
  BureaucratVoteStatus,
  BureaucratVoteWorkshopRef,
  ResearchRecipeId,
  ResearchLineStatus,
  ResearchJobStatus,
  ResearchDestination,
  RelationshipState,
  ResearchLabItemSnapshot,
  ResearchLabLine,
  ResearchJobKind,
  ResearchLabSignalKind,
  ResearchLabJob,
  NpcRelationship,
  NpcRelationshipEvent,
  NpcConversationMessage,
  NpcConversation,
  ResearchContributionRankingRow,
  ResearchHallOfFameResponse,
  ResearchRankingDiscordPayload,
  ResearchRankingState,
  TeamResearchContribution,
  HonorDomain,
  OperationHonorCategory,
  HonorCategory,
  HonorRecordStatus,
  HonorSourceType,
  HonorRecordSource,
  HonorEvidenceAudit,
  HonorCharacterIdentity,
  OperationHonorSourceCandidate,
  OperationHonorSourceSegment,
  OperationHonorSourceMaterial,
  NovexHonorFallbackPerformance,
  HonorRecord,
  UpsertHonorRecordInput,
  HonorAnalysisStatus,
  HonorAnalysisState,
  HonorRecordQuery,
  HonorRecordPage,
} from "./types/index.js";

export {
  USER_ROLES,
  USER_STATUSES,
  AGENT_LEVELS,
  AGENT_LEVEL_LABELS,
  CHARACTER_TIERS,
  ROLE_LEVELS,
  ROLE_LEVEL_RANK,
  DEPARTMENTS,
  FACTIONS,
  INSTITUTIONS,
  INTERNAL_FACTION_CODE,
  CREDIT_TRANSACTION_TYPES,
  WEB_ALLOWED_CREDIT_TYPES,
  GM_DIRECT_GRANT_TYPES,
  BOT_ONLY_CREDIT_TYPES,
  isGmDirectGrantType,
  EQUIPMENT_SLOTS,
  ITEM_CATEGORIES,
  OPERATION_POOL_ID,
  OPERATION_POOL_DEFAULT_NAME,
  OPERATION_POOL_INITIAL_BALANCE,
  PLAYER_TRADE_KINDS,
  PLAYER_TRADE_STATUSES,
  SCHEDULED_JOB_RUN_STATUSES,
  INTEGRATION_OUTBOX_STATUSES,
  INTEGRATION_OUTBOX_KINDS,
  INTEGRATION_DELIVERY_OUTCOMES,
  INTEGRATION_SKIP_REASONS,
  LORE_ENTITY_KINDS,
  LORE_RECORD_STATUSES,
  LORE_VISIBILITIES,
  LORE_SOURCE_KINDS,
  LORE_SOURCE_LOCATOR_KINDS,
  LORE_LINEAGE_STATES,
  LORE_ALIAS_TYPES,
  LORE_INGESTION_MODES,
  LORE_INGESTION_STATUSES,
  LORE_DOMAIN_SEARCH_PROJECTION_OWNER,
  BUREAUCRAT_VOTE_BUTTON_PREFIX,
  BUREAUCRAT_VOTE_CHANNEL_ID,
  BUREAUCRAT_VOTE_CONTENT_MAX_LENGTH,
  BUREAUCRAT_VOTE_DURATION_MS,
  BUREAUCRAT_VOTE_TITLE_MAX_LENGTH,
  RESEARCH_RECIPE_IDS,
  RESEARCH_LINE_STATUSES,
  RESEARCH_JOB_STATUSES,
  RESEARCH_DESTINATIONS,
  RELATIONSHIP_STATES,
  RESEARCH_INITIAL_DURATION_MS,
  RESEARCH_REPEAT_DURATION_MS,
  RESEARCH_CLAIM_WINDOW_MS,
  RESEARCH_CLAIM_REMINDER_LEAD_MS,
  RESEARCH_REPEAT_CREDIT_COST,
  STOCK_MARKET_STATE_ID,
  RESEARCH_RANKING_STATE_COLLECTION,
  RESEARCH_RANKING_STATE_ID,
  HONOR_DOMAINS,
  OPERATION_HONOR_CATEGORIES,
  HONOR_ANALYSIS_STATUSES,
  HONOR_ANALYZER_REVISION,
  HONOR_MANUAL_REVIEW_REVISION,
  HONOR_ANALYSIS_SOURCE_MAX_CHARS,
} from "./types/index.js";

/* ── Client ── */

export type { SharedDbConfig } from "./client.js";
export {
  initServerless,
  connect,
  close,
  getClient,
  getDb,
  getClientSync,
  getDbSync,
} from "./client.js";

/* ── Collections (async) ── */

export {
  usersCol,
  sessionsCol,
  sessionResponsesCol,
  sessionLogsCol,
  userTipsCol,
  charactersCol,
  creditTransactionsCol,
  creditBalancesCol,
  masterItemsCol,
  characterInventoryCol,
  sharedInventoryCol,
  wikiPagesCol,
  wikiPageRevisionsCol,
  sessionReportsCol,
  notificationsCol,
  honorRecordsCol,
  honorAnalysisStatesCol,
  factionsCol,
  institutionsCol,
  creditPoolsCol,
  shopInventoryCol,
  shopDailyStockCol,
  stockPricesCol,
  stockHoldingsCol,
  stockPriceHistoryCol,
  playerTradesCol,
  trpgSessionsCol,
  trpgGuildMembersCol,
  trpgSessionNotificationsCol,
  scheduledJobRunsCol,
  integrationOutboxCol,
  mrBeastSodaStockImpactDemandCol,
  workerCheckpointsCol,
  workerOperationalIncidentsCol,
  loreSourcesCol,
  loreAliasesCol,
  loreEdgesCol,
  loreClaimsCol,
  loreSearchDocumentsCol,
  loreIngestionRunsCol,
  bureaucratVotesCol,
  researchLabLinesCol,
  researchLabJobsCol,
  npcRelationshipsCol,
  npcRelationshipEventsCol,
  npcConversationsCol,
} from "./collections.js";

/* ── Collections (sync, long-running only) ── */

export {
  usersColSync,
  sessionsColSync,
  sessionResponsesColSync,
  sessionLogsColSync,
  userTipsColSync,
  charactersColSync,
  creditTransactionsColSync,
  creditBalancesColSync,
  masterItemsColSync,
  characterInventoryColSync,
  sharedInventoryColSync,
  wikiPagesColSync,
  wikiPageRevisionsColSync,
  sessionReportsColSync,
  notificationsColSync,
  honorRecordsColSync,
  honorAnalysisStatesColSync,
  factionsColSync,
  institutionsColSync,
  creditPoolsColSync,
  shopInventoryColSync,
  shopDailyStockColSync,
  stockPricesColSync,
  stockHoldingsColSync,
  stockPriceHistoryColSync,
  playerTradesColSync,
  trpgSessionsColSync,
  trpgGuildMembersColSync,
  trpgSessionNotificationsColSync,
  scheduledJobRunsColSync,
  integrationOutboxColSync,
  mrBeastSodaStockImpactDemandColSync,
  workerCheckpointsColSync,
  workerOperationalIncidentsColSync,
  loreSourcesColSync,
  loreAliasesColSync,
  loreEdgesColSync,
  loreClaimsColSync,
  loreSearchDocumentsColSync,
  loreIngestionRunsColSync,
  bureaucratVotesColSync,
  researchLabLinesColSync,
  researchLabJobsColSync,
  npcRelationshipsColSync,
  npcRelationshipEventsColSync,
  npcConversationsColSync,
} from "./collections.js";

/* ── Indexes ── */

export {
  ensureAllIndexes,
  ensureLoreIndexes,
  ensureSessionReportIndexes,
  ensureBureaucratVoteIndexes,
  ensureResearchLabIndexes,
  ensureNovexIndexes,
  ensureHonorIndexes,
  findLoreUniqueIndexConflicts,
  LORE_INDEX_DEFINITIONS,
  SESSION_REPORT_INDEX_DEFINITIONS,
  BUREAUCRAT_VOTE_INDEX_DEFINITIONS,
  RESEARCH_LAB_INDEX_DEFINITIONS,
  NOVEX_INDEX_DEFINITIONS,
  HONOR_INDEX_DEFINITIONS,
} from "./indexes.js";
export { ensureChangeLogsIndexes } from "./migrations/ensure-change-logs-indexes.js";
export {
  inspectNovex2Migration,
  applyNovex2Migration,
  migrateLegacyPendingStockDisclosures,
  legacyPendingEventContentHash,
  nextNovexSlotAfter,
  findNovex2LegacyPriceEffectConflicts,
  novex2MigrationPlanFingerprint,
  novex2MigrationReadinessBlockers,
  getNovex2MigrationReadiness,
  claimNovex2MigrationReadiness,
  recoverNovex2MigrationReadiness,
} from "./migrations/novex-2-transition.js";
export type {
  NormalizedIndexSpec,
  Novex2IndexPlanSpec,
  Novex2LegacyPendingEventSpec,
  Novex2LegacyPriceEffectConflict,
  Novex2MigrationPlan,
  Novex2MigrationReadiness,
  Novex2MigrationReadinessRecoveryMode,
  Novex2MigrationReadinessRecoveryResult,
  Novex2MigrationResult,
  Novex2ReferencePriceBackfillSpec,
  Novex2TtlIndexSpec,
  Novex2UniqueIndexCheck,
} from "./migrations/novex-2-transition.js";

/* ── Utils ── */

export { isValidObjectId } from "./utils.js";
export {
  buildOperationHonorSourceMaterial,
  sanitizeOperationHonorSourceText,
} from "./honor-source.js";

/* ── Discord delivery routing ── */

export {
  JTEST_WORKSHOP_DISCORD_DM_MIRROR_RULE,
  resolveDiscordDmRecipients,
} from "./discord-dm-recipients.js";
export type {
  DiscordDmMirrorRule,
  DiscordDmRecipient,
  DiscordDmRecipientKind,
  DiscordDmRecipientResolution,
  DiscordDmSourceState,
} from "./discord-dm-recipients.js";

/* ── CRUD ── */

export * from "./crud/index.js";

/* ── Schemas (zod) ── */

export * from "./schemas/index.js";
