/* ── Types ── */

export type {
  User,
  UserRole,
  UserStatus,
  UserPublic,
  CreateUserInput,
  Session,
  SessionResponse,
  SessionStatus,
  ResponseStatus,
  ResponseCounts,
  SessionFinalizationKind,
  SessionFinalizationTrigger,
  SessionFinalizationDeliveryState,
  SessionFinalizationReconciliationReason,
  SessionLog,
  SessionLogType,
  Character,
  AgentCharacter,
  NpcCharacter,
  CharacterType,
  CharacterTier,
  AgentLevel,
  RoleLevel,
  DepartmentCode,
  FactionCode,
  InstitutionCode,
  LegacyDepartmentCode,
  LoreSheet,
  DossierRelation,
  DossierRelationConfidence,
  DossierSessionAppearance,
  PlaySheet,
  Equipment,
  Ability,
  AbilitySlot,
  CreateCharacterInput,
  CharacterPublic,
  CreditTransaction,
  CreditBalance,
  CreditTransactionType,
  CreateCreditTransactionInput,
  WebAllowedCreditType,
  GmDirectGrantType,
  BotOnlyCreditType,
  MasterItem,
  CharacterInventory,
  SharedInventory,
  SharedInventoryScope,
  ItemCategory,
  EquipmentSlot,
  EquipmentAction,
  EquipmentChargeState,
  LicenseQualification,
  ShopMeta,
  ShopPageGroup,
  CreateMasterItemInput,
  CreateInventoryInput,
  CreateSharedInventoryInput,
  WikiPage,
  WikiPageLite,
  WikiPageRevision,
  CreateWikiPageInput,
  UpdateWikiPageInput,
  Notification,
  NotificationType,
  CreateNotificationInput,
  SessionReport,
  SessionReportMapPrecision,
  CreateSessionReportInput,
  RegistrarUserTip,
  CharacterChangeLog,
  CharacterChangeLogEntry,
  NewCharacterChangeLog,
  CreditPool,
  CreateCreditPoolInput,
  ShopInventory,
  ShopDailyStock,
  CreateShopInventoryInput,
  CreateShopDailyStockInput,
  StockPrice,
  StockHolding,
  StockPriceHistory,
  CreateStockPriceInput,
  CreateStockHoldingInput,
  CreateStockPriceHistoryInput,
  PlayerTrade,
  PlayerTradeKind,
  PlayerTradeStatus,
  PlayerTradeParticipant,
  PlayerTradeOffer,
  PlayerTradeItemOffer,
  PlayerTradeStockOffer,
  CreatePlayerTradeInput,
  TrpgSession,
  TrpgSessionStatus,
  UpdateTrpgSessionResult,
  CancelTrpgSessionResult,
  TrpgGuildMember,
  TrpgSessionNotification,
  TrpgNotificationKind,
  TrpgNotificationDeliveryMethod,
  ScheduledJobRun,
  ScheduledJobRunStatus,
  IntegrationOutboxEvent,
  IntegrationOutboxStatus,
  IntegrationOutboxKind,
  WorkerCheckpoint,
} from "./types/index.js";

export {
  USER_ROLES,
  USER_STATUSES,
  AGENT_LEVELS,
  AGENT_LEVEL_LABELS,
  CHARACTER_TIERS,
  ROLE_LEVELS,
  ROLE_LEVEL_RANK,
  DEPARTMENTS,
  FACTIONS,
  INSTITUTIONS,
  INTERNAL_FACTION_CODE,
  CREDIT_TRANSACTION_TYPES,
  WEB_ALLOWED_CREDIT_TYPES,
  GM_DIRECT_GRANT_TYPES,
  BOT_ONLY_CREDIT_TYPES,
  isGmDirectGrantType,
  EQUIPMENT_SLOTS,
  ITEM_CATEGORIES,
  OPERATION_POOL_ID,
  OPERATION_POOL_DEFAULT_NAME,
  OPERATION_POOL_INITIAL_BALANCE,
  PLAYER_TRADE_KINDS,
  PLAYER_TRADE_STATUSES,
  SCHEDULED_JOB_RUN_STATUSES,
  INTEGRATION_OUTBOX_STATUSES,
  INTEGRATION_OUTBOX_KINDS,
} from "./types/index.js";

/* ── Client ── */

export type { SharedDbConfig } from "./client.js";
export {
  initServerless,
  connect,
  close,
  getClient,
  getDb,
  getClientSync,
  getDbSync,
} from "./client.js";

/* ── Collections (async) ── */

export {
  usersCol,
  sessionsCol,
  sessionResponsesCol,
  sessionLogsCol,
  userTipsCol,
  charactersCol,
  creditTransactionsCol,
  creditBalancesCol,
  masterItemsCol,
  characterInventoryCol,
  sharedInventoryCol,
  wikiPagesCol,
  wikiPageRevisionsCol,
  sessionReportsCol,
  notificationsCol,
  factionsCol,
  institutionsCol,
  creditPoolsCol,
  shopInventoryCol,
  shopDailyStockCol,
  stockPricesCol,
  stockHoldingsCol,
  stockPriceHistoryCol,
  playerTradesCol,
  trpgSessionsCol,
  trpgGuildMembersCol,
  trpgSessionNotificationsCol,
  scheduledJobRunsCol,
  integrationOutboxCol,
  workerCheckpointsCol,
} from "./collections.js";

/* ── Collections (sync, long-running only) ── */

export {
  usersColSync,
  sessionsColSync,
  sessionResponsesColSync,
  sessionLogsColSync,
  userTipsColSync,
  charactersColSync,
  creditTransactionsColSync,
  creditBalancesColSync,
  masterItemsColSync,
  characterInventoryColSync,
  sharedInventoryColSync,
  wikiPagesColSync,
  wikiPageRevisionsColSync,
  sessionReportsColSync,
  notificationsColSync,
  factionsColSync,
  institutionsColSync,
  creditPoolsColSync,
  shopInventoryColSync,
  shopDailyStockColSync,
  stockPricesColSync,
  stockHoldingsColSync,
  stockPriceHistoryColSync,
  playerTradesColSync,
  trpgSessionsColSync,
  trpgGuildMembersColSync,
  trpgSessionNotificationsColSync,
  scheduledJobRunsColSync,
  integrationOutboxColSync,
  workerCheckpointsColSync,
} from "./collections.js";

/* ── Indexes ── */

export { ensureAllIndexes } from "./indexes.js";
export { ensureChangeLogsIndexes } from "./migrations/ensure-change-logs-indexes.js";

/* ── Utils ── */

export { isValidObjectId } from "./utils.js";

/* ── Discord delivery routing ── */

export {
  JTEST_DISCORD_DM_MIRROR_RULE,
  resolveDiscordDmRecipients,
} from "./discord-dm-recipients.js";
export type {
  DiscordDmMirrorRule,
  DiscordDmRecipient,
  DiscordDmRecipientKind,
  DiscordDmRecipientResolution,
  DiscordDmSourceState,
} from "./discord-dm-recipients.js";

/* ── CRUD ── */

export * from "./crud/index.js";

/* ── Schemas (zod) ── */

export * from "./schemas/index.js";
