import type { ComponentType, SVGProps } from 'react'

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>

export { IconApply } from './IconApply'
export { IconArchive } from './IconArchive'
export { IconArrowLeft } from './IconArrowLeft'
export { IconArrowRight } from './IconArrowRight'
export { IconBullet } from './IconBullet'
export { IconCharacter } from './IconCharacter'
export { IconChevronDown } from './IconChevronDown'
export { IconChevronLeft } from './IconChevronLeft'
export { IconChevronRight } from './IconChevronRight'
export { IconChevronUp } from './IconChevronUp'
export { IconClose } from './IconClose'
export { IconContact } from './IconContact'
export { IconCredit } from './IconCredit'
export { IconCrown } from './IconCrown'
export { IconDashboard } from './IconDashboard'
export { IconDivider } from './IconDivider'
export { IconEquipment } from './IconEquipment'
export { IconMembers } from './IconMembers'
export { IconMenu } from './IconMenu'
export { IconNotes } from './IconNotes'
export { IconNotification } from './IconNotification'
export { IconPlayer } from './IconPlayer'
export { IconProfile } from './IconProfile'
export { IconReturn } from './IconReturn'
export { IconRules } from './IconRules'
export { IconSession } from './IconSession'
export { IconSystem } from './IconSystem'
export { IconUserAdmin } from './IconUserAdmin'
export { IconWiki } from './IconWiki'
export { IconWorld } from './IconWorld'
