/**
 * seed-payload JSON upsert helper.
 *
 * Supports lore/data publication payloads generated by stargate-lore:
 *   - characters      filter: { codename }
 *   - wiki_pages      filter: { slug }
 *   - master_items    filter: { slug }
 *   - factions        filter: { code }
 *   - institutions    filter: { code }
 *   - session_reports filter: { sessionId }
 *   - equipment_workshop_blueprints filter: { slug }
 *
 * Envelopes may either contain:
 *   - payload: full/partial $set upsert payload keyed by the collection filter
 *   - update: explicit MongoDB update document plus filter for additive updates
 *   - allowQuestionMarkPlaceholder: 사용자 승인 literal "???"를 허용하는 opt-in
 *
 * Economy mutations are intentionally not supported here. Use reviewed,
 * domain-specific scripts/API paths for credit ledgers, inventory grants, shop
 * stock, purchases/consumption, and stock trades/prices.
 *
 * Usage:
 *   pnpm run seed:payload -- scripts/seed-payloads/npc-doctor-moss.json
 *   pnpm run seed:payload -- scripts/seed-payloads/npc-doctor-moss.json --execute --yes
 *   pnpm run seed:payload -- scripts/seed-payloads --execute --yes --verbose
 */

import { existsSync, readFileSync, readdirSync, statSync } from "fs";
import { resolve } from "path";

import { MongoClient, type Collection, type Document } from "mongodb";

import type { DossierPersonalityObservation } from "@stargate/shared-db/types";

import {
  appendPersonalityObservation,
  classifyPersonalityObservationWrite,
  extractPersonalityObservationUpdate,
  toProtectedCharacterSetPayload,
  validateInitialPersonalityObservations,
  withParsedInitialPersonalityObservations,
  withParsedPersonalityObservation,
} from "./lib/personality-observation-update.ts";

/* ── env ─────────────────────────────────────────────────────────────── */

function loadEnvFile(fileName: string): void {
  const envPath = resolve(process.cwd(), fileName);
  try {
    const envContent = readFileSync(envPath, "utf-8");
    for (const line of envContent.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      let val = trimmed.slice(eqIdx + 1).trim();
      if (
        (val.startsWith("\"") && val.endsWith("\"")) ||
        (val.startsWith("'") && val.endsWith("'"))
      ) {
        val = val.slice(1, -1);
      }
      if (process.env[key] === undefined) process.env[key] = val;
    }
  } catch {
    // Optional file. Actual execution checks MONGODB_URI later.
  }
}

loadEnvFile(".env.local");
loadEnvFile(".env");

/* ── cli ─────────────────────────────────────────────────────────────── */

const EXECUTE = process.argv.includes("--execute");
const YES = process.argv.includes("--yes");
const DRY_RUN = !EXECUTE;
const VERBOSE = process.argv.includes("--verbose") || process.argv.includes("-v");

const INPUT_ARGS = process.argv
  .slice(2)
  .filter((arg) => !arg.startsWith("-"));

if (EXECUTE && !YES) {
  console.error("[seed-payload] --execute 시 --yes 확인이 필요합니다.");
  console.error("  dry-run: pnpm run seed:payload -- <payload.json>");
  console.error(
    "  write:   pnpm run seed:payload -- <payload.json> --execute --yes",
  );
  process.exit(1);
}

if (INPUT_ARGS.length === 0) {
  console.error("[seed-payload] payload JSON 파일 또는 디렉토리를 지정하세요.");
  console.error("  예: pnpm run seed:payload -- scripts/seed-payloads");
  process.exit(1);
}

const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = process.env.DB_NAME ?? "stargate";

if (EXECUTE && MONGODB_URI) {
  try {
    console.log(`[seed-payload] WRITE 대상 호스트: ${new URL(MONGODB_URI).host}`);
  } catch {
    console.log("[seed-payload] WRITE 모드 (MONGODB_URI 호스트 파싱 실패)");
  }
}

/* ── types ───────────────────────────────────────────────────────────── */

type SupportedCollection =
  | "characters"
  | "wiki_pages"
  | "master_items"
  | "factions"
  | "institutions"
  | "session_reports"
  | "equipment_workshop_blueprints";

interface SeedPayloadEnvelope {
  collection: SupportedCollection;
  type?: string;
  payload?: Record<string, unknown>;
  filter?: Record<string, unknown>;
  update?: Record<string, unknown> | Record<string, unknown>[];
  upsert?: boolean;
  allowQuestionMarkPlaceholder?: boolean;
}

interface UpsertPlan {
  file: string;
  collection: SupportedCollection;
  mode: "payload" | "update";
  filter: Record<string, unknown>;
  payload?: Record<string, unknown>;
  update?: Record<string, unknown> | Record<string, unknown>[];
  upsert?: boolean;
  allowQuestionMarkPlaceholder?: boolean;
  personalityObservation?: DossierPersonalityObservation;
  initialPersonalityObservations?: DossierPersonalityObservation[];
}

interface UpsertResultSummary {
  file: string;
  collection: SupportedCollection;
  filter: Record<string, unknown>;
  action:
    | "예상 insert"
    | "예상 update"
    | "예상 missing"
    | "예상 unchanged"
    | "예상 미상"
    | "inserted"
    | "updated"
    | "unchanged";
  id?: string;
  verification?: Record<string, unknown>;
}

const SUPPORTED_COLLECTIONS = new Set<SupportedCollection>([
  "characters",
  "wiki_pages",
  "master_items",
  "factions",
  "institutions",
  "session_reports",
  "equipment_workshop_blueprints",
]);

/* ── input loading ───────────────────────────────────────────────────── */

function collectJsonFiles(inputs: string[]): string[] {
  const files: string[] = [];
  for (const input of inputs) {
    const fullPath = resolve(process.cwd(), input);
    if (!existsSync(fullPath)) {
      throw new Error(`[seed-payload] 입력 경로가 없습니다: ${input}`);
    }
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      for (const name of readdirSync(fullPath)) {
        if (name.toLowerCase().endsWith(".json")) {
          files.push(resolve(fullPath, name));
        }
      }
      continue;
    }
    if (!input.toLowerCase().endsWith(".json")) {
      throw new Error(`[seed-payload] JSON 파일만 지원합니다: ${input}`);
    }
    files.push(fullPath);
  }
  return files.sort((a, b) => a.localeCompare(b, "en"));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function parseEnvelope(file: string): SeedPayloadEnvelope[] {
  const raw = JSON.parse(readFileSync(file, "utf-8")) as unknown;
  const entries = Array.isArray(raw) ? raw : [raw];
  return entries.map((entry, index) => {
    if (!isRecord(entry)) {
      throw new Error(`[seed-payload] ${file}#${index}: 객체가 아닙니다.`);
    }
    const collection = entry.collection;
    if (
      typeof collection !== "string" ||
      !SUPPORTED_COLLECTIONS.has(collection as SupportedCollection)
    ) {
      throw new Error(
        `[seed-payload] ${file}#${index}: 지원하지 않는 collection=${String(collection)}`,
      );
    }
    const hasPayload = isRecord(entry.payload);
    const hasUpdate =
      isRecord(entry.update) ||
      (Array.isArray(entry.update) && entry.update.every(isRecord));
    if (!hasPayload && !hasUpdate) {
      throw new Error(
        `[seed-payload] ${file}#${index}: payload 또는 update 객체가 필요합니다.`,
      );
    }
    return {
      collection: collection as SupportedCollection,
      type: typeof entry.type === "string" ? entry.type : undefined,
      payload: hasPayload
        ? (entry.payload as Record<string, unknown>)
        : undefined,
      filter: isRecord(entry.filter) ? entry.filter : undefined,
      update: hasUpdate
        ? (entry.update as Record<string, unknown> | Record<string, unknown>[])
        : undefined,
      upsert: typeof entry.upsert === "boolean" ? entry.upsert : undefined,
      allowQuestionMarkPlaceholder:
        entry.allowQuestionMarkPlaceholder === true,
    };
  });
}

/* ── payload normalization ───────────────────────────────────────────── */

function looksLikeIsoDate(value: string): boolean {
  return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(value);
}

function shouldCoerceDate(key: string, value: unknown): value is string {
  return (
    typeof value === "string" &&
    looksLikeIsoDate(value) &&
    (key.endsWith("At") || key === "date")
  );
}

function normalizeDates(value: unknown, key = ""): unknown {
  if (value instanceof Date) return value;
  if (shouldCoerceDate(key, value)) return new Date(value);
  if (Array.isArray(value)) return value.map((item) => normalizeDates(item));
  if (!isRecord(value)) return value;

  const result: Record<string, unknown> = {};
  for (const [childKey, childValue] of Object.entries(value)) {
    result[childKey] = normalizeDates(childValue, childKey);
  }
  return result;
}

function omitMongoManagedFields(payload: Record<string, unknown>): {
  setPayload: Record<string, unknown>;
  createdAt: Date | undefined;
} {
  const normalized = normalizeDates(payload) as Record<string, unknown>;
  const { createdAt, ...rest } = normalized;
  delete rest._id;
  return {
    setPayload: rest,
    createdAt: createdAt instanceof Date ? createdAt : undefined,
  };
}

function requireString(
  payload: Record<string, unknown>,
  key: string,
  collection: SupportedCollection,
): string {
  const value = payload[key];
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`[seed-payload] ${collection}: payload.${key} 문자열이 필요합니다.`);
  }
  return value.trim();
}

function buildFilter(
  collection: SupportedCollection,
  payload: Record<string, unknown>,
): Record<string, unknown> {
  switch (collection) {
    case "characters":
      return { codename: requireString(payload, "codename", collection) };
    case "wiki_pages":
      return { slug: requireString(payload, "slug", collection) };
    case "master_items":
    case "equipment_workshop_blueprints":
      return { slug: requireString(payload, "slug", collection) };
    case "factions":
    case "institutions":
      return { code: requireString(payload, "code", collection) };
    case "session_reports":
      return { sessionId: requireString(payload, "sessionId", collection) };
  }
}

function buildPlans(files: string[]): UpsertPlan[] {
  const plans: UpsertPlan[] = [];
  for (const file of files) {
    for (const envelope of parseEnvelope(file)) {
      let payload = envelope.payload
        ? (normalizeDates(envelope.payload) as Record<string, unknown>)
        : undefined;
      const filter = envelope.filter
        ? (normalizeDates(envelope.filter) as Record<string, unknown>)
        : payload
          ? buildFilter(envelope.collection, payload)
          : undefined;
      if (!filter) {
        throw new Error(
          `[seed-payload] ${file}: update envelope에는 filter가 필요합니다.`,
        );
      }
      if (envelope.update) {
        const normalizedUpdate = normalizeDates(envelope.update) as
          | Record<string, unknown>
          | Record<string, unknown>[];
        const personalityObservation =
          envelope.collection === "characters"
            ? extractPersonalityObservationUpdate(normalizedUpdate)
            : null;
        if (personalityObservation && envelope.upsert === true) {
          throw new Error(
            `[seed-payload] personality observation append는 기존 character만 대상으로 하며 upsert를 허용하지 않습니다: ${file}`,
          );
        }
        plans.push({
          file,
          collection: envelope.collection,
          mode: "update",
          filter,
          update:
            personalityObservation && !Array.isArray(normalizedUpdate)
              ? withParsedPersonalityObservation(
                  normalizedUpdate,
                  personalityObservation,
                )
              : normalizedUpdate,
          upsert: envelope.upsert === true,
          allowQuestionMarkPlaceholder:
            envelope.allowQuestionMarkPlaceholder === true,
          personalityObservation: personalityObservation ?? undefined,
        });
        continue;
      }
      if (!payload) {
        throw new Error(`[seed-payload] ${file}: payload가 필요합니다.`);
      }
      const initialPersonalityObservations =
        envelope.collection === "characters"
          ? validateInitialPersonalityObservations(payload)
          : null;
      if (initialPersonalityObservations !== null) {
        payload = withParsedInitialPersonalityObservations(
          payload,
          initialPersonalityObservations,
        );
      }
      plans.push({
        file,
        collection: envelope.collection,
        mode: "payload",
        filter,
        payload,
        initialPersonalityObservations:
          initialPersonalityObservations ?? undefined,
        allowQuestionMarkPlaceholder:
          envelope.allowQuestionMarkPlaceholder === true,
      });
    }
  }
  return plans;
}

/* ── verification ────────────────────────────────────────────────────── */

function hasBadText(value: unknown): boolean {
  if (typeof value === "string") {
    return value.includes("\uFFFD") || value.includes("???");
  }
  if (Array.isArray(value)) return value.some((item) => hasBadText(item));
  if (!isRecord(value)) return false;
  return Object.values(value).some((item) => hasBadText(item));
}

function hasReplacementCharacter(value: unknown): boolean {
  if (typeof value === "string") return value.includes("\uFFFD");
  if (Array.isArray(value)) {
    return value.some((item) => hasReplacementCharacter(item));
  }
  if (!isRecord(value)) return false;
  return Object.values(value).some((item) => hasReplacementCharacter(item));
}

function summarizeSavedDoc(
  collection: SupportedCollection,
  doc: Document,
): Record<string, unknown> {
  const base = {
    id: doc._id ? String(doc._id) : undefined,
    textIntegrity: hasBadText(doc) ? "warning" : "ok",
  };

  switch (collection) {
    case "characters":
      return {
        ...base,
        codename: doc.codename,
        type: doc.type,
        isPublic: doc.isPublic,
        agentLevel: doc.agentLevel,
        factionCode: doc.factionCode,
        institutionCode: doc.institutionCode,
        department: doc.department,
        previewImage: doc.previewImage,
        appearsInEvents: isRecord(doc.lore)
          ? doc.lore.appearsInEvents
          : undefined,
        relationCount:
          isRecord(doc.lore) && Array.isArray(doc.lore.relations)
            ? doc.lore.relations.length
            : 0,
        sessionAppearanceCount:
          isRecord(doc.lore) && Array.isArray(doc.lore.sessionAppearances)
            ? doc.lore.sessionAppearances.length
            : 0,
        personalityObservationCount:
          isRecord(doc.lore) && Array.isArray(doc.lore.personalityObservations)
            ? doc.lore.personalityObservations.length
            : 0,
        personalityObservationIds:
          isRecord(doc.lore) && Array.isArray(doc.lore.personalityObservations)
            ? doc.lore.personalityObservations
                .filter(isRecord)
                .map((observation) => observation.id)
                .filter((id): id is string => typeof id === "string")
            : [],
        personnelVisible: doc.isPublic !== false && doc.type === "NPC",
      };
    case "wiki_pages":
      return {
        ...base,
        slug: doc.slug,
        title: doc.title,
        category: doc.category,
        isPublic: doc.isPublic,
        tags: doc.tags,
      };
    case "master_items":
      return {
        ...base,
        slug: doc.slug,
        name: doc.name,
        category: doc.category,
        price: doc.price,
        isPublic: doc.isPublic,
        isAvailable: doc.isAvailable,
        tags: doc.tags,
      };
    case "equipment_workshop_blueprints":
      return {
        ...base,
        slug: doc.slug,
        displayName: doc.displayName,
        version: doc.version,
        status: doc.status,
        sourceClass: doc.sourceClass,
        balanceStatus: doc.balanceStatus,
      };
    case "factions":
    case "institutions":
      return {
        ...base,
        code: doc.code,
        slug: doc.slug,
        label: doc.label,
        isPublic: doc.isPublic,
      };
    case "session_reports":
      return {
        ...base,
        sessionId: doc.sessionId,
        sessionTitle: doc.sessionTitle,
        createdAt: doc.createdAt,
        updatedAt: doc.updatedAt,
        locationLabel: doc.locationLabel,
        mapPrecision: doc.mapPrecision,
      };
  }
}

function printSummary(summary: UpsertResultSummary): void {
  const marker = summary.action.startsWith("예상") ? "[plan]" : "[done]";
  const filter = JSON.stringify(summary.filter);
  console.log(`  ${marker} ${summary.collection.padEnd(15)} ${filter} | ${summary.action}`);
  if (summary.id) console.log(`     id: ${summary.id}`);
  if (VERBOSE && summary.verification) {
    console.log(`     verification: ${JSON.stringify(summary.verification, null, 2)}`);
  }
}

/* ── main ────────────────────────────────────────────────────────────── */

async function dryRunWithoutDb(plans: UpsertPlan[]): Promise<void> {
  console.warn(
    "[seed-payload] MONGODB_URI 미설정 — DB 조회 없이 계획만 출력합니다.",
  );
  for (const plan of plans) {
    printSummary({
      file: plan.file,
      collection: plan.collection,
      filter: plan.filter,
      action: "예상 미상",
    });
  }
}

async function dryRunWithDb(
  colByName: Map<SupportedCollection, Collection<Document>>,
  plans: UpsertPlan[],
): Promise<void> {
  for (const plan of plans) {
    const col = colByName.get(plan.collection);
    if (!col) throw new Error(`[seed-payload] collection handle 누락: ${plan.collection}`);
    const needsPersonalityState =
      plan.personalityObservation !== undefined ||
      plan.initialPersonalityObservations !== undefined;
    const existing = await col.findOne(plan.filter, {
      projection: needsPersonalityState
        ? { _id: 1, "lore.personalityObservations": 1 }
        : { _id: 1 },
    });
    if (existing && plan.initialPersonalityObservations !== undefined) {
      throw new Error(
        `[seed-payload] 최초 personality observations가 포함된 character payload는 기존 문서를 갱신할 수 없습니다: ${JSON.stringify(plan.filter)}`,
      );
    }
    const personalityAction =
      existing && plan.personalityObservation
        ? classifyPersonalityObservationWrite(
            existing,
            plan.personalityObservation,
          )
        : null;
    printSummary({
      file: plan.file,
      collection: plan.collection,
      filter: plan.filter,
      action: existing
        ? personalityAction === "unchanged"
          ? "예상 unchanged"
          : "예상 update"
        : plan.mode === "payload" || plan.upsert
          ? "예상 insert"
          : "예상 missing",
      id: existing?._id ? String(existing._id) : undefined,
    });
  }
}

async function writeWithDb(
  colByName: Map<SupportedCollection, Collection<Document>>,
  plans: UpsertPlan[],
): Promise<void> {
  for (const plan of plans) {
    const col = colByName.get(plan.collection);
    if (!col) throw new Error(`[seed-payload] collection handle 누락: ${plan.collection}`);

    const needsPersonalityState =
      plan.personalityObservation !== undefined ||
      plan.initialPersonalityObservations !== undefined;
    const existing = await col.findOne(plan.filter, {
      projection: needsPersonalityState
        ? { _id: 1, "lore.personalityObservations": 1 }
        : { _id: 1 },
    });
    let writtenId = existing?._id;
    let unchanged = false;
    if (plan.mode === "update") {
      if (!plan.update) {
        throw new Error(`[seed-payload] update plan 누락: ${plan.collection}`);
      }
      if (!existing && !plan.upsert) {
        throw new Error(
          `[seed-payload] update 대상 없음: ${plan.collection} ${JSON.stringify(plan.filter)}`,
        );
      }
      if (plan.personalityObservation) {
        if (Array.isArray(plan.update)) {
          throw new Error(
            `[seed-payload] personality observation pipeline update는 지원하지 않습니다.`,
          );
        }
        const result = await appendPersonalityObservation(
          col,
          plan.filter,
          plan.update,
          plan.personalityObservation,
        );
        writtenId = result.id as typeof writtenId;
        unchanged = result.status === "unchanged";
      } else {
        const result = await col.updateOne(
          plan.filter,
          plan.update as Document | Document[],
          { upsert: plan.upsert === true },
        );
        if (result.matchedCount + result.upsertedCount !== 1) {
          throw new Error(
            `[seed-payload] update CAS 불일치: ${plan.collection} ${JSON.stringify(plan.filter)}`,
          );
        }
        writtenId ??= result.upsertedId ?? undefined;
      }
    } else {
      if (!plan.payload) {
        throw new Error(`[seed-payload] payload plan 누락: ${plan.collection}`);
      }
      const { setPayload, createdAt } = omitMongoManagedFields(plan.payload);
      if (setPayload.updatedAt === undefined) setPayload.updatedAt = new Date();

      if (plan.initialPersonalityObservations !== undefined) {
        if (existing) {
          throw new Error(
            `[seed-payload] 최초 personality observations가 포함된 character payload는 기존 문서를 갱신할 수 없습니다: ${JSON.stringify(plan.filter)}`,
          );
        }
        const result = await col.insertOne({
          ...setPayload,
          createdAt: createdAt ?? new Date(),
        });
        writtenId = result.insertedId;
      } else {
        const protectedSetPayload =
          plan.collection === "characters"
            ? toProtectedCharacterSetPayload(setPayload)
            : setPayload;
        const result = await col.updateOne(
          plan.filter,
          {
            $set: protectedSetPayload,
            $setOnInsert: { createdAt: createdAt ?? new Date() },
          },
          { upsert: true },
        );
        if (result.matchedCount + result.upsertedCount !== 1) {
          throw new Error(
            `[seed-payload] payload upsert 실패: ${plan.collection} ${JSON.stringify(plan.filter)}`,
          );
        }
        writtenId ??= result.upsertedId ?? undefined;
      }
    }

    const saved = writtenId
      ? await col.findOne({ _id: writtenId })
      : await col.findOne(plan.filter);
    if (!saved) {
      throw new Error(
        `[seed-payload] write 후 재조회 실패: ${plan.collection} ${JSON.stringify(plan.filter)}`,
      );
    }

    const verification = summarizeSavedDoc(plan.collection, saved);
    printSummary({
      file: plan.file,
      collection: plan.collection,
      filter: plan.filter,
      action: unchanged ? "unchanged" : existing ? "updated" : "inserted",
      id: saved._id ? String(saved._id) : undefined,
      verification,
    });

    if (
      verification.textIntegrity === "warning" &&
      !(
        plan.allowQuestionMarkPlaceholder &&
        !hasReplacementCharacter(saved)
      )
    ) {
      throw new Error(
        `[seed-payload] text integrity warning: ${plan.collection} ${JSON.stringify(plan.filter)}`,
      );
    }
    if (verification.textIntegrity === "warning") {
      console.warn(
        `[seed-payload] 사용자 승인 literal "???" 허용: ${plan.collection} ${JSON.stringify(plan.filter)}`,
      );
    }
  }
}

async function main(): Promise<void> {
  const files = collectJsonFiles(INPUT_ARGS);
  const plans = buildPlans(files);

  if (plans.length === 0) {
    console.warn("[seed-payload] 처리할 payload가 없습니다.");
    return;
  }

  console.log(
    `[seed-payload] ${DRY_RUN ? "DRY-RUN" : "WRITE"} 모드 | files=${files.length} | payloads=${plans.length}`,
  );

  if (!MONGODB_URI) {
    if (EXECUTE) {
      console.error("[seed-payload] MONGODB_URI 환경변수가 설정되지 않았습니다.");
      process.exit(1);
    }
    await dryRunWithoutDb(plans);
    return;
  }

  const client = new MongoClient(MONGODB_URI);
  await client.connect();
  try {
    const db = client.db(DB_NAME);
    const colByName = new Map<SupportedCollection, Collection<Document>>(
      [...SUPPORTED_COLLECTIONS].map((name) => [name, db.collection(name)]),
    );

    if (DRY_RUN) {
      await dryRunWithDb(colByName, plans);
    } else {
      await writeWithDb(colByName, plans);
    }
  } finally {
    await client.close();
  }
}

main().catch((err) => {
  console.error("[seed-payload] 실패:", err);
  process.exit(1);
});
